apiVersion: v1
kind: Namespace
metadata:
  name: kubesnooze
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesnooze
  namespace: kubesnooze
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesnooze
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesnooze
subjects:
  - kind: ServiceAccount
    name: kubesnooze
    namespace: kubesnooze
roleRef:
  kind: ClusterRole
  name: kubesnooze
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesnooze
  namespace: kubesnooze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesnooze
  template:
    metadata:
      labels:
        app: kubesnooze
    spec:
      serviceAccountName: kubesnooze
      nodeSelector:
        sleep-target: "true"

      volumes:
        - name: system-power
          hostPath:
            - path: /sys/power/state
              type: File
      containers:
        - name: kubesnooze
          image: ghcr.io/FlomoN/kubesnooze:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: WATCHED_DEPLOYMENTS
              value: "default/app1,default/app2" # Example value, modify as needed
            - name: TIMER_DURATION
              value: "1h" # Example value, modify as needed
          volumeMounts:
            - name: system-power
              mountPath: /sys/power/state
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
